# Generated by Django 2.2.20 on 2021-07-06 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo_photo', to='expenses.Expense')),
            ],
        ),
    ]
